### ISSUE TITLE
file size in much bigger in IOS  compared to Android 

### ISSUE THREAD

**Issue by chandanrai95** [dooboolab/react-native-audio-recorder-player#101]

**Comment by hyochan** [comment]
You should update [this](https://github.com/dooboolab/react-native-audio-recorder-player/blob/a33e8da3e319e26a85760b368a92306f0bb84d4f/ios/RNAudioRecorderPlayer.m#L122-L126) in order to change the size. The `parameter` passed down are not customizable currently, however, I'll support this in the future.

**Comment by taimoornaj** [comment]
I'm using that library currently the file size is too big how can i reduce the file size
