### ISSUE TITLE
BREAKING CHANGE

### ISSUE THREAD

**Issue by netbull** [dooboolab/react-native-audio-recorder-player#120]
### Version of react-native-audio-recorder-player
latest version

### Platforms you faced the error (IOS or Android or both?)
both

startRecorder first argument is broken/non consistent between both OS!

Now iOS forces to use relative path and prepends the app temp directory to the path, but on android an absolute path should be provided, because it does not prepend the temp directory.

Why this behaviour was made?

**Comment by hyochan** [comment]
Well, if I remember correctly, I think it didn't quite work well to make `dir` without an existing path maybe because of the `permission`.  If you know the better approach, please give us a `PR`.

**Comment by netbull** [comment]
@hyochan the issues are:
- that there is no consistency between `iOS` and `android`. iOS requires a relative path, but android  an absolute
- for iOS we are forced to use the temp app dir.

My opinion is to allow both platforms to use absolute paths and to fallback to the temp app dir.

**Comment by hyochan** [comment]
Thanks for comming back! Could you kindly provide a PR please?

**Comment by netbull** [comment]
@hyochan the PR is not a problem, just I need to know your idea behind making that change in the iOS platform /the android is fine/

**Comment by hyochan** [comment]
I think there was some issue in [#94](https://github.com/dooboolab/react-native-audio-recorder-player/pull/94). I've not had much time to review this.

**Comment by netbull** [comment]
Ok, when I have enough time I'll make "proper" PR :)

**Comment by hyochan** [comment]
@netbull Thank you!

**Comment by hyochan** [comment]
@netbull Also, please edit `index.ts` file only and run `yarn build` or `npm run build` to generate `index.js`, `index.d.ts`, `index.flow.js` and run it on your example project. This project is not `typescript` based.

**Comment by escobar5** [comment]
@netbull, @hyochan My PR does exactly that,  I removed the line where the path was prepended to the temp directory in iOS, so I could pass it a different directory to save the recording. If I'm understanding it right, that's what @netbull is asking for.

The thing is, tough the PR was merged, there is no version available with that change, so maybe that's why @netbull is still experiencing it.

**Comment by hyochan** [comment]
@escobar5 Could you guide the changes again? I've had crashing issue report in earlier issues related to the changes in `android`. I hope we can check the changes once more.

**Comment by escobar5** [comment]
@hyochan what do you mean with "guide the changes again"? also, can you point me to the crashing issue?

**Comment by hyochan** [comment]
@escobar5 I am sorry that I've confused you. I've reverted your work as seen in [line of code](https://github.com/dooboolab/react-native-audio-recorder-player/blob/b906d8a62469850e7d1b866521569318656287ed/ios/RNAudioRecorderPlayer.m#L127) because I couldn't resolve the path with the code you've given. Could you kindly test your `PR` on `ios` again for directory path and path individually? Such as `/path/file.m4a` and `file.m4a` for `ios`.

**Comment by escobar5** [comment]
Oh ok, I understand now, sure, let me check it again
