### ISSUE TITLE
It fails to stop when the recording is less than a second

### ISSUE THREAD

**Issue by preduseldavid** [dooboolab/react-native-audio-recorder-player#203]
I get this error when the recording is less than a second:
![Screenshot_1589797818](https://user-images.githubusercontent.com/47463852/82203387-ec843a00-990b-11ea-8c27-040a89bfb6e0.png)

**Comment by rolivegab** [comment]
Hi!
I fixed that issue in my fork.
It was a simple solution, and i think it really solves the problem.
That bug happens when you try to stop recording too fast.
It is explained here: https://stackoverflow.com/questions/16221866/mediarecorder-failed-when-i-stop-the-recording

I'm newbie, so i don't know how to submit a PR here, but if any maintainer wants me to submit the PR, i can try to.

**Comment by preduseldavid** [comment]
thank you @rolivegab. @hyochan is this package abandoned?
