### ISSUE TITLE
unable to send authorization token on server when playing file from url

### ISSUE THREAD

**Issue by AndreiToader1** [dooboolab/react-native-audio-recorder-player#229]
### Expected behavior
Send authorization token for the url when playing file from the server
### Actual behavior
Authorization is not supported when playing file from url
### Steps to reprodue the behabior
I have the following snippet:
const playPausePlayer = async () => {
const audioUrl = "https://server-url/attachments/VoiceFile_0.mp4";
  if (isPlaying) {
    console.log("WAS PLAYING");
    stopPlayer();
    isPlaying = false;
    return;
  }
  try {
    const msg = await audioRecorderPlayer.startPlayer(audioUrl);
    console.log(msg);
    isPlaying = !isPlaying;
  } catch(e) {
    console.log(e);
  }
}
const stopPlayer = async () => {
  audioRecorderPlayer.stopPlayer();
  audioRecorderPlayer.removePlayBackListener();
}

The code works fine when 
https://server-url/attachments/VoiceFile_0.mp4 is not authorized. The problem is that we have a bearer token a bearer token authorization so we should be able to send the token to the startPlayer method.
something like:
const msg = await audioRecorderPlayer.startPlayer(audioUrl, authroizationToken);

Please note that the url is a dummy one since the server where we do the call is not public on the internet

**Comment by hyochan** [comment]
I will pay for this weekend! Sorry for the delay!

**Comment by hyochan** [comment]
@AndreiToader1 You can now pass `httpHeaders` when `startPlayer`. I've done this in `android`. Also, I am not sure if this is also needed in `iOS`. Please tell me. Since, I've not tested this strictly, I hope you can test this out which is released in `2.6.0-rc1`. Will remove `rc` when this feature is working well.

**Comment by hyochan** [comment]
To make this work on iOS, I found it that we need to migrate `AVAudioPlayer` which we currently used to `AVPlayer` followed by [the article](https://stackoverflow.com/questions/15456130/add-custom-header-field-in-request-of-avplayer).

The problem is now is that I only have my Chromebook and I don't have a mac. Therefore, I can't refactor this and test previous features that are working well.
