### ISSUE TITLE
Parameter path should be a path and not a file name on iOS

### ISSUE THREAD

**Issue by escobar5** [dooboolab/react-native-audio-recorder-player#90]
### Version of react-native-audio-recorder-player
2.2.0
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
on method startRecorder, the parameter named path doesn't work as a path on iOS, it's just the fileName, it should be a path, on Android it works as a path. 
This has some issues:
- The functionality is inconsistent between both platforms
- I can't save the iOS recording in a different location, just a different filename.

### Actual behavior
The parameter passed to startRecorder is a fileName.

**Comment by escobar5** [comment]
@hyochan I can make the change, do you consider it will be better that way?

**Comment by hyochan** [comment]
@escobar5 Sure! Please give a PR 🙏🏻

**Comment by mdathersajjad** [comment]
Please update the docs regarding this path issue. In the Readme tips sections it is mentioned to give the filename as sound.m4a and it will return the uri since this code is merged it won't work. The file wont be available. It will be better to include a constants which will give the temp path in ios and android
